--DROP TABLE tblTPProdOptions

CREATE TABLE tblTPProdOptions

(
	TPProdOptionID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	ProductTypeID INT NOT NULL,
	ProductID INT NOT NULL,
	DocType INT NOT NULL,
	DocPath VARCHAR(1000),	



	Remark VARCHAR(500),
	Creator VARCHAR(50) DEFAULT SUSER_SNAME(),
    DateCreate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Editor VARCHAR(50) DEFAULT SUSER_SNAME(),
    DateEdit DATETIME DEFAULT CURRENT_TIMESTAMP,


)


Go

--SELECT * FROM tblTPProdOptions